View(Bill_and_comp_common)
Bill_and_comp_common1=Bill_and_comp_common
dim(Bill_and_comp_common1)
names(Bill_and_comp_common1)
str(Bill_and_comp_common1$X1)
class(Bill_and_comp_common1$X1)
class(Bill_and_comp_common1$cust_id)
class(Bill_and_comp_common1$act_active_dt)
class(Bill_and_comp_common1$package_id)
class(Bill_and_comp_common1$bill_zip)
class(Bill_and_comp_common1$customer_segment)
class(Bill_and_comp_common1$status)
class(Bill_and_comp_common1$bill_amt)
sum(is.na(Bill_and_comp_common1$X1))
sum(is.na(Bill_and_comp_common1$cust_id))
sum(is.na(Bill_and_comp_common1$act_active_dt))
sum(is.na(Bill_and_comp_common1$package_id))
sum(is.na(Bill_and_comp_common1$bill_zip))
sum(is.na(Bill_and_comp_common1$customer_segment))
sum(is.na(Bill_and_comp_common1$status))
sum(is.na(Bill_and_comp_common1$bill_amt))
summary(is.na(Bill_and_comp_common1))
summary(duplicated(Bill_and_comp_common1))
mean(Bill_and_comp_common1$package_id,na.rm = TRUE)
mean(is.na(Bill_and_comp_common1$customer_segment))
names(Bill_and_comp_common1)
unlist(sapply(Bill_and_comp_common1, class))
unlist(lapply(Bill_and_comp_common1, class))
str(Bill_and_comp_common1)
